name: Android CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Load Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          gradle-
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unit tests
      run: ./gradlew check
    - name: Save Test Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-reports
        path: app/build/reports
    - name: Upload to codecoverage
        uses: codecov/codecov-action@v1
        with:
          directory: ./app/build/test-results
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}